### ISSUE TITLE
Build fails with firebase dependency

### ISSUE THREAD

**Issue by ggajews** [google/TestParameterInjector#10]
This library is using `protobuf-java` dependency which clashes with Firebase library which contains `protobuf-javalite`.
I'm not sure if there is a way to resolve this dependency issue.

My android instrumentation builds fails with multiple errors like this:

```Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.14.0 (com.google.protobuf:protobuf-java:3.14.0) and jetified-protobuf-lite-3.0.1 (com.google.protobuf:protobuf-lite:3.0.1)```

**Comment by nymanjens** [comment]
It feels like your problem would be solved if we changed the `protobuf` dependency to `protobuf-lite`.

I tried this and everything seems to build, so unless anyone objects, you can expect a release for this early next week.

**Comment by ggajews** [comment]
👍 thanks!

**Comment by nymanjens** [comment]
I just released v1.4, with the protobuf-lite replacement. It'll probably take O(hours) before it is distributed across all channels.
