### ISSUE TITLE
Running a single test using maven verify

### ISSUE THREAD

**Issue by ArvindJoshi-okta** [google/TestParameterInjector#35]
**Problem**
I am unable to run a single test method using `mvn verify`. 

**Scenario**
My test class has a combination of parameterized tests (using `@TestParameters`) and a bunch of other tests that aren't parameterized. 
When executing tests for the entire class using `-Dit.test=MyClass`, all tests (including the parameterized ones execute). But when I run a specific test method using `-Dit.test=MyClass#MyParameterizedTestMethod`, no tests get executed. 

Issue exists when using the `@TestParameter` annotation as well.

**Comment by nymanjens** [comment]
The test names are in the form:

```
MyClass#MyParameterizedTestMethod[foo=true,bar=false]
```

Can you try adding a `*` at the end of the query?

```
-Dit.test=MyClass#MyParameterizedTestMethod*
```

**Comment by ArvindJoshi-okta** [comment]
Great, that worked @nymanjens . Could we please add that to the documentation? Thanks!
