### ISSUE TITLE
Does this work with Powermock libraries?

### ISSUE THREAD

**Issue by ArvindJoshi-okta** [google/TestParameterInjector#40]
Hi,
 I am having issues when using `TestParameterInjector` with powermock libraries. To be specific, when I use `PowerMockRunnerDelegate`, I get the following error:

```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(TestParameterInjector.class)
```

```
java.lang.IllegalStateException: Expected exactly one constructor, but got [protected SomeClass(org.powermock.core.IndicateReloadClass), public SomeClass()]
```

**Comment by nymanjens** [comment]
The class under test should have a default constructor, so you could check that.

If there is no obvious error there, we don't explicitly support Powermock. If you think there is a fix that we could do on our side to support Powermock, I'm happy to consider it.

**Comment by ArvindJoshi-okta** [comment]
Constructor present or absent in the class under test doesn't seem to make a difference. The powermock delegation seems to be creating an additional constructor. 
I haven't yet looked at a possible solution, but wondering what is the purpose of this check for a single constructor?

https://github.com/google/TestParameterInjector/blob/main/junit4/src/main/java/com/google/testing/junit/testparameterinjector/TestParametersMethodProcessor.java#L447

**Comment by ArvindJoshi-okta** [comment]
One potential fix would be check for the public constructor and use that to get the annotations? 

```
  private ImmutableList<Optional<TestParametersValues>>
      getConstructorParametersOrSingleAbsentElement(Class<?> testClass) {
    Constructor<?> constructor = getOnlyConstructor(testClass);
    return hasRelevantAnnotation(constructor)
        ? FluentIterable.from(getConstructorParameters(constructor))
            .transform(Optional::of)
            .toList()
        : ImmutableList.of(Optional.absent());
  }
```

**Comment by ArvindJoshi-okta** [comment]
Here's a fix that I tried locally and works, change is in `getOnlyConstructor`. Thoughts?

```
if (constructors.size() > 1 && testClass.isAnnotationPresent(PowerMockRunnerDelegate.class)) {
      for (Constructor<?> constructor : constructors) {
        if (Modifier.isPublic(constructor.getModifiers())) {
          return getOnlyElement(ImmutableList.of(constructor));
        }
      }
    }
```

**Comment by ArvindJoshi-okta** [comment]
Upon further investigation, it looks like the issue happens only when `PowerMockRunner` and `EasyMockSupport` is used. For example, I was able to repro the issue with the following class in this repo.

```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(TestParameterInjector.class)
public class PowerMockDelegateTest extends EasyMockSupport {

  public PowerMockDelegateTest() {

  }

  @Test
  public void test(@TestParameter boolean parameter) {
    assertThat(this.getClass().getAnnotation(PowerMockRunnerDelegate.class).annotationType())
            .isEqualTo(PowerMockRunnerDelegate.class);
  }
}
```

**Comment by nymanjens** [comment]
Looks the test runner itself is using `getTestClass().getOnlyConstructor()`, which is probably modified by Powermock to do the right thing. But then later, the following custom method is called by TestParameterInjector:

```
  private static Constructor<?> getOnlyConstructor(Class<?> testClass) {
    ImmutableList<Constructor<?>> constructors =
        ImmutableList.copyOf(testClass.getDeclaredConstructors());
    checkState(
        constructors.size() == 1, "Expected exactly one constructor, but got %s", constructors);
    return getOnlyElement(constructors);
  }
```

Ideally, we'd use `getTestClass().getOnlyConstructor()` throughout the codebase, but that's a big refactor. Instead, I'm thinking of being more lenient and filtering out non-public constructors first and let `getTestClass().getOnlyConstructor()` do the validation.

**Comment by nymanjens** [comment]
Could you check locally if this works?

```
import static com.google.common.collect.MoreCollectors.onlyElement;

constructors.stream().filter(c -> Modifier.isPublic(c.getModifiers())).collect(onlyElement())
```

**Comment by ArvindJoshi-okta** [comment]
yes, this works, @nymanjens

**Comment by ArvindJoshi-okta** [comment]
Are you planning to push your change? @nymanjens

**Comment by nymanjens** [comment]
I didn't have time this week, but I'll try to do it next week.

**Comment by ArvindJoshi-okta** [comment]
great, thank you so much!
