### ISSUE TITLE
Integrate with RobolectricTestRunner

### ISSUE THREAD

**Issue by AlanChiou** [google/TestParameterInjector#5]
If we test an Android component(Activity, Fragment, Service...) with [Robolectric](http://robolectric.org/), we will use [`RobolectricTestRunner`](http://robolectric.org/writing-a-test/) as the test runner.

And a test class only have a test runner.
I also find a way to run a test class within multiple test runners, but I have no idea if it works with TestParameterInjector.
https://bekce.github.io/junit-multiple-runwith-dependent-tests/

Could you have a look about this topic?
Is possible that using TestParameterInjector as a [Rule](https://junit.org/junit4/javadoc/4.12/org/junit/Rule.html)?

**Comment by nymanjens** [comment]
> Is possible that using TestParameterInjector as a Rule?

AFAIK, that's not possible in JUnit4, unfortunately. The only solution I think is to make a test runner that combines `RobolectricTestRunner` and `TestParameterInjector` or modify `RobolectricTestRunner` to support `TestParameterInjector` annotations.

We have an internal feature request to do this second option (`RobolectricTestRunner` to support the `TestParameterInjector` annotations). However, I'm being told this might either be a lot of work or practically impossible. I'll update this thread if we make any progress here.

**Comment by jleskovar-tyro** [comment]
Hi @nymanjens - just wanted to check-in as to whether there was any progress with this? Thanks!

**Comment by nymanjens** [comment]
I'm on vacation right now, but I'll check when I get back

**Comment by nymanjens** [comment]
Update: Internally in Google, we have an implementation that combines RobolectricTestRunner with TestParameterInjector. It was introduced about 2 years ago and its usage has been growing rapidly.

I checked with the author, and they are confident that it is stable enough to make it open source. There was an issue of it depending on a Google-internal part of TestParameterInjector, but I'm fixing that now.

**Comment by alexvanyo** [comment]
The [4.14-beta-1](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.14-beta-1) release of Robolectric includes the new `RobolectricTestParameterInjector` that integrates with `TestParameterInjector` using the newly exposed APIs in `TestParameterInjector` `1.18`.

**Comment by nymanjens** [comment]
Great! Looks like the change made it to a public release :-).
